services:
  postgres:
    image: postgres:15-alpine
    container_name: kmedtour-postgres
    environment:
      POSTGRES_DB: kmedtour
      POSTGRES_USER: kmedtour
      POSTGRES_PASSWORD: kmedtour
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: kmedtour-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
